/** Declaration file generated by dts-gen */
declare module 'bootstrap-vue' {

    /*export function install(Vue: any): void;

    export namespace install {
        const prototype: {
        };

    }*/
    
    let BootstrapVue:any;
    
    export default BootstrapVue;

}

